const actionsTypes = {
  COUNTER_DECREMENT: 'COUNTER_DECREMENT',
  COUNTER_INCREMENT: 'COUNTER_INCREMENT',
  ADD_COMIC_TO_LIST: 'ADD_COMIC_TO_LIST',
  REMOVE_COMIC_FROM_LIST: 'REMOVE_COMIC_FROM_LIST'
}

export { actionsTypes }
